export const TIMELINE_LABEL = {
  FIRST_SECTION: {
    LEFT_SIDE: 'FIRST_SECTION_LEFT_SIDE',
    RIGHT_SIDE: 'FIRST_SECTION_RIGHT_SIDE',
  },
  SECOND_SECTION: {
    TEXT: 'SECOND_SECTION_TEXT',
    IMAGE: 'SECOND_SECTION_IMAGE',
  },
};

export const ANIMATION_DURATION = 0.5;

export const ANIMATION_DURATION_SECOND_SECTION_IMG = 1;
